# Generated by Django 3.2.9 on 2022-01-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('sensor', models.TextField()),
                ('iso', models.TextField()),
                ('procesador', models.TextField()),
                ('precio', models.TextField()),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MR', 'Mirrorless'), ('DSLR', 'DSRL')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Montura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EF', 'EF'), ('EF-S', 'EF-S'), ('EF-M', 'EF-M')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('USM', 'USM'), ('STM', 'STM'), ('MACRO', 'MACRO'), ('MANUAL', 'MANUAL')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_focal', models.TextField()),
                ('apertura', models.TextField()),
                ('estabilizador', models.CharField(max_length=2)),
                ('montura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.montura')),
                ('motor_enfoque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.motor')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.TextField(null=True)),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.camara')),
                ('objetivos', models.ManyToManyField(to='main.Objetivo')),
            ],
        ),
        migrations.AddField(
            model_name='camara',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.categoria'),
        ),
    ]
