# Generated by Django 3.2.9 on 2022-01-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camara',
            name='marca',
        ),
        migrations.AddField(
            model_name='camara',
            name='foto',
            field=models.ImageField(default='//i1.adis.ws/i/canon/4728C033_EOS-M50-Mark-II_01/4728c033_eos-m50-mark-ii_01?w=1500&bg=rgb(245,246,246)&fmt=jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camara',
            name='precio',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
